# Numpy Practice - Hints - Unibs 2021

#### Import the numpy package under the name `np` and print version and configuration (base)
`hint: import … as, np.__version__, np.show_config`

In [1]:
import numpy as np
print(f"NumPy version: {np.__version__}")

# Print NumPy configuration
print("\nNumPy configuration:")
np.show_config()

NumPy version: 2.0.2

NumPy configuration:
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.11.8/lib/python3.11/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.11.8/lib/python3.11/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Zen MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.27
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.11.8/lib/python3.11/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.11.8/lib/python3.11/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Zen MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.27
Compilers:
  c:
    com

## Base Practice

#### 1. Create a null vector of size 10 but the fifth value which is 1 (base)
`hint: array[4]`

In [2]:
array = np.zeros(10)
array[4] = 1
print(array)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 2. Create a 3x3 matrix with values ranging from 0 to 8 with zeros on the diagonal (base)
`hint: np.arange, reshape, np.eye`

In [3]:
matrix = np.arange(9).reshape(3, 3)
np.fill_diagonal(matrix, 0)
matrix

array([[0, 1, 2],
       [3, 0, 5],
       [6, 7, 0]])

#### 3. How to add a border (filled with 0's) around an 5x5 matrix of ones? (base)
`hint: np.ones, np.pad`

In [4]:
matrix = np.ones((5, 5))
matrix_with_border = np.pad(matrix, pad_width=1, mode='constant', constant_values=0)

print(matrix_with_border)


[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


#### 4. Normalize a 5x5 random matrix (base)
`hint: (x - mean) / std, np.mean, np.std`

In [5]:
random_matrix = np.random.random((5, 5))

x = (random_matrix - np.mean(random_matrix)) / np.std(random_matrix)
print(x)

[[-1.46647399 -1.31351664  0.72210549  0.14634741  1.70648036]
 [-0.68028757  1.32867526  1.14029257  1.64666255 -0.1049528 ]
 [-0.65373487  1.5533545  -1.16676688  0.53555298 -0.81362814]
 [-0.16797085 -1.20540149  0.11012415 -0.91243238 -0.1326536 ]
 [-1.0772638  -1.03597508  0.51454502  1.18571369  0.14120413]]


#### 5. Multiply a 5x3 matrix of ones by a 3x2 matrix of ones (real matrix product) (base)
`hint: np.dot`

In [6]:
np.dot(np.ones((5, 3)), np.ones((3, 2)))

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

## Intermediate Practice

#### 6. Create a vector of size 10 with values ranging from 0 to 1, both excluded (intermediate)
`hint: np.linspace`

In [7]:
#vettore di 12 elementi, rimuove il primo e l'ultimo
vector1 = np.linspace(0, 1, 12)[1:-1]
print(vector1)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 7. Create a random vector of size 10 with values in range (-3, 12) and sort it (intermediate)
`hint: sort`

In [11]:
random_vector = np.random.randint(-3, 12, size=10)
sorted_vector = np.sort(random_vector)
sorted_vector


array([-3, -2,  0,  0,  4,  5,  6,  9, 10, 11])

#### 8. Create random vector of size 10 and replace the maximum value by its additive inverse and the minimum value (of the original array) with the median value (intermediate)
`hint: argmax, argmin`

In [20]:
random_vector = np.random.randint(0, 100, 10)
print(random_vector)

max_value = np.max(random_vector)
max_index = np.argmax(random_vector)
print(f"Valore massimo: {max_value} at index {max_index}")

min_value = np.min(random_vector)
min_index = np.argmin(random_vector)
print(f"Valore minimo: {min_value} at index {min_index}")

median_value = np.median(random_vector)
random_vector[max_index] = -max_value
random_vector[min_index] = median_value
print(random_vector)

[91 59 70 43  7 46 34 77 80 35]
Valore massimo: 91 at index 0
Valore minimo: 7 at index 4
[-91  59  70  43  52  46  34  77  80  35]


#### 9. Randomly replace p elements in a 2D nxn zero matrix to 1 (intermediate)
`hint: np.put, np.random.choice`

In [30]:
def random_ones_matrix(n):
    p = np.random.randint(1, n*n)
    matrix = np.zeros((n, n), dtype=int)
    indices = np.random.choice(n*n, size=p, replace=False)
    np.put(matrix, indices, 1)
    return matrix

result = random_ones_matrix(n)
print(result)

[[1 0 1 0 0]
 [1 1 0 1 0]
 [1 1 0 0 0]
 [0 1 1 0 1]
 [0 0 1 1 0]]


#### 10. Subtract the mean of each row of a random 5x10 matrix (intermediate)
`hint: mean(axis=,keepdims=)`

In [34]:
matrix = np.random.rand(5, 10)
row_means = np.mean(matrix, axis=1, keepdims=True)
centered_matrix = matrix - row_means
print(centered_matrix)

[[ 0.14903314  0.05972885 -0.41490499 -0.14086395 -0.24337739 -0.26459011
   0.4644308  -0.11548203  0.3834668   0.12255887]
 [ 0.35358767  0.06141345  0.13568025  0.05129406 -0.24598065  0.28122848
  -0.16045128 -0.41690767  0.20424866 -0.26411296]
 [ 0.2069932   0.22046319  0.18139901 -0.36330668 -0.71800877  0.19485318
  -0.30528123  0.23318944  0.23015459  0.11954407]
 [-0.19288326 -0.10223443  0.36380452 -0.17041015 -0.31783941  0.06946911
   0.44882262  0.20869764  0.08272902 -0.39015566]
 [ 0.0215873   0.39663392 -0.45333591 -0.07509027  0.28395315  0.14734869
   0.10359582  0.10906416 -0.23392877 -0.29982808]]
