# Numpy Practice - Hints - Unibs 2021

#### Import the numpy package under the name `np` and print version and configuration (base)
`hint: import … as, np.__version__, np.show_config`

In [6]:
import numpy as np
print(f"NumPy version: {np.__version__}")

# Print NumPy configuration
print("\nNumPy configuration:")
np.show_config()

NumPy version: 2.0.2

NumPy configuration:
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.11.8/lib/python3.11/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.11.8/lib/python3.11/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Zen MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.27
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.11.8/lib/python3.11/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.11.8/lib/python3.11/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Zen MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.27
Compilers:
  c:
    com

## Base Practice

#### 1. Create a null vector of size 10 but the fifth value which is 1 (base)
`hint: array[4]`

In [10]:
array = np.zeros(10)
array[4] = 1
print(array)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 2. Create a 3x3 matrix with values ranging from 0 to 8 with zeros on the diagonal (base)
`hint: np.arange, reshape, np.eye`

In [19]:
matrix = np.arange(9).reshape(3, 3)
np.fill_diagonal(matrix, 0)
matrix

array([[0, 1, 2],
       [3, 0, 5],
       [6, 7, 0]])

#### 3. How to add a border (filled with 0's) around an 5x5 matrix of ones? (base)
`hint: np.ones, np.pad`

In [23]:
matrix = np.ones((5, 5))
matrix_with_border = np.pad(matrix, pad_width=1, mode='constant', constant_values=0)

print(matrix_with_border)


[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


#### 4. Normalize a 5x5 random matrix (base)
`hint: (x - mean) / std, np.mean, np.std`

In [26]:
random_matrix = np.random.random((5, 5))

x = (random_matrix - np.mean(random_matrix)) / np.std(random_matrix)
print(x)

[[ 0.03805251  0.70786839  1.39389469 -0.98690241 -1.00988023]
 [ 0.10262303 -0.20503958  1.03090816 -0.81208577  0.52384893]
 [-1.24395022  1.04872472  0.14575736 -2.0448978   1.75813044]
 [ 0.67898875  0.78329781 -0.54139459 -2.00661695  0.4026258 ]
 [-0.37649096  1.05251516  0.51242997 -1.20021168  0.24780444]]


#### 5. Multiply a 5x3 matrix of ones by a 3x2 matrix of ones (real matrix product) (base)
`hint: np.dot`

In [29]:
np.dot(np.ones((5, 3)), np.ones((3, 2)))

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

## Intermediate Practice

#### 6. Create a vector of size 10 with values ranging from 0 to 1, both excluded (intermediate)
`hint: np.linspace`

In [34]:
#vettore di 12 elementi, rimuove il primo e l'ultimo
vector1 = np.linspace(0, 1, 12)[1:-1]
print(vector1)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 7. Create a random vector of size 10 with values in range (-3, 12) and sort it (intermediate)
`hint: sort`

AttributeError: module 'numpy' has no attribute 'randrange'

In [40]:
random_vector = np.random.randint(-3, 12, size=10)
sorted_vector = np.sort(random_vector)
sorted_vector


array([-2, -1, -1,  0,  5,  6,  6,  6,  7,  7])

#### 8. Create random vector of size 10 and replace the maximum value by its additive inverse and the minimum value (of the original array) with the median value (intermediate)
`hint: argmax, argmin`

#### 9. Randomly replace p elements in a 2D nxn zero matrix to 1 (intermediate)
`hint: np.put, np.random.choice`

#### 10. Subtract the mean of each row of a random 5x10 matrix (intermediate)
`hint: mean(axis=,keepdims=)`